* FAQ
** How much will I need to pay?
£12 per month is payed to the squadron to cover the runing costs, but activities off squadron (exlcuding camps) are free.
** How old do i need to be?
12 and a half AND in year 8 or above
** Do i have to join the RAF if I join Cadets?
No. Cadets is all about giving teenagers the chance to learn new skills, take risks and meet new people. If you don’t want to joing the air force, thats totally fine, you don’t have too. Equally, if you want to join the RAF, joining air cadets will help you to understand the sort of life and dicipline you will be facing and what the RAF expect from you.
** Can girls join?
The Air cadets as an organisation don’t discriminate against any race, gender or sexuality, all can join. 
** Do I have to buy the uniform?
No, we provide you with most of the uniform. The only thing you have to buy are parade shoes, combat boots and a greens belt. These are not too expensive if you buy them from the right places. If you come along to a recruitment day, we will tell you the best places to buy these things.
** What are the rules on cosmetics and jewellery?
Only discreet makeup is permitted, discreet enough so that only you should really know its there. Nail varnish must be natural colours only. Piercings are also not allowed to be worn on any Cadet activity, as well as Necklaces, chains and Bracelets.
** Is it really strict?
The Air Cadets have a rank system which will require all lower ranks to obey the higher ranking cadet. Failiure to act approppriately or obey orders will result in consequences. There is a dress code which cadets are expected to follow, but generally we do not consider our squadron or the cadets as a whole to be overly strict.
** Is it all about marching?
All cadets are taught to be able to correctly execute drill movements and commands. At the beginning and end of each night there are instances of drill / marching, but this is not often the focus of whole nights. Each night is something different, and there are many enjoyable activities that teens would otherwise not have access to.
** What are the rules on hair?
Boys: Hair cannot touch your collar or ears, but as long as it fits inside your beret, it is permitted.
Girls: Hair cannot touch your collar or ears, all hair must be put into a bun and your fringe must be pinned back. You can still have long hair.
** I have a disability, can I still join?
Absolutely! You are very welcome providing you can take part in a reasonable number of activities and as long as your disability does not cause you safety problems. Squadron staff will be happy to speak to you about this.
