* Duke Of Endiburgh Award
You may of heard of the DofE (Duke of Edinburgh) Award, but don't know what it is or whether it's for you. Well, it's for everyone who likes a challenge. Their mission is simple - 'to inspire, guide and support young people in their self-development, and recognise their achievements'.

To put it another way, they help you succeed. With the same sense of adventure that drew you to the Air Cadets in the first place, the DofE takes you through a programme of activities that will leave you a more confident, motivated and capable person.

We're proud to be the DofE Award's largest participant.

If you're 14 or over, then you can begin - just ask the instructors in your squadron and they'll help you get started. For more information now on everything DofE, follow any of the links on this page to visit their official website.

There are three levels which, when successfully completed, lead to a Bronze, Silver or Gold DofE Award. And it's never too late to get in on the action - depending on your age you may be able to jump straight in at Silver or Gold level!

There are four sections at Bronze and Silver level and five at Gold:

- Volunteering - Get involved providing services to individuals or the community and make a difference to other people's lives

- Physical - Get active and improve your skills and fitness in sport, dance or other physical activities - it's your choice

- Skills - Find new interests and get new talents (or perfect existing ones), with increased practical and social skills

- Expedition - Get outdoors and plan, train for and complete an adventurous journey in the UK or abroad - an unbeatable experience

- Residential - Only at Gold level. Getting to the Gold level is a big deal and this last stage could see you going to another country, sharing tasks and activities with people you've never met. It'll test your mettle, and set you up for what life throws at you in the future

It's not a walk in the park. You'll get your DofE Award through persistence and commitment - but as an Air Cadet you'll already know all about that. Over time you'll develop personally and welcome each new challenge. At the end of it all you'll have the world’s leading achievement award for young people under your belt, recognised by employers and universities alike.

But there's one person who'll truly appreciate that achievement the most - you.

For more information visit http://www.dofe.org/.
