* Drill
What's the point of drill and parade? You may think it doesn't have much to do with things like adventurous training, or leadership. That's not the case at all! It shows how disciplined and organised you can be as an individual, remembering instructions and carrying them out accurately. More importantly, it shows your ability to work in a team and is a way of displaying the high standards of dress and behaviour which air cadets are renowned for.

Teamwork
When a group of twenty cadets walk on to a parade square they are all individuals, but as soon as a session of drill begins the cadets become a team, following the orders given by one person. Instead of twenty individual feet hitting the ground, there is only one sound. This is the result of practice and teamwork.
Drill is also used when you are moving around in large groups in a smart, orderly fashion. Whatever the reason for a drill it's an impressive sight and shows civilians and members of the Forces just how well disciplined you are.

 
As a cadet you'll participate in various forms of drill, such as:

- Foot Drill
- Basic Drill (both quick & slow time)
- Banner Drill
- Band Drill

With a few years experience, and if you've attained a Non-Commissioned Officer rank, you could pass on your knowledge and experience to other cadets, instructing them on how to participate in a drill squad, taking charge of a drill squad yourself, or even playing a major part in ceremonial drill. Being a Standard Bearer at a Remembrance Day parade is a real moment of pride and achievement for a cadet.
