* Flying and Gliding
** Flying
The chance to go flying is offered to every cadet within the Air Training Corps. As part of 1325 'Dinnington' Sqn you will be taken to 9 Air Experience Fight at RAF Linton-en-Ouse to get chance to fly a Grob Tutor with an experienced RAF pilot. You will also get the chance to undertake aerobatics.
** Gliding
Within the Air Training Corps cadets will have the opportunity to go gliding in one of two of the organisations gliders. This is a very fun experience and both gliders are very different from each other. The Viking is a winch launched glider, this sees the glider get pulled up into the air by a metal rope. The Vigilant is a motor glider, this means it has an engine and and a propeller. This allows the glider to take off and land like a conventional aircraft but during the flight the engine is powered almost fully down so that it acts like a glider.
** Scholarships
The Air Training Corps offers both gliding and flying scholarships to cadets that get recommended for them, this gives the cadets the opportunity to gain their wings and go solo in the aircraft.
