* Shooting
** No.8 Rifle
The first rifle that a cadet is eligible to fire is the No.8 rifle, it is a bolt action rifle that started its life out as the Enfield No 4 rifle, used as far back as World War II. Modified to have a shorter barrel and fire the .22 long rifle round, it no longer takes a box magazine holding 10 rounds - you feed in each round manually. It makes little noise, although ear defenders are always worn on the range, and is a great first step for your marksmanship skills. 'Dry training' is the first thing you'll do - exploring the No.8 in detail, and learning the commands and safety practices used on the range. After you've successfully passed the Weapon Handling Test (WHT) you'll be ready to progress onto the range.
** L98 Cadet GP Rifle
Over 14? Then you can handle the L98A2 Cadet GP rifle (L98) which is the next step up from the No.8 . This rifle is modified from the Enfield L85A2 which is currently in active service. It is re-cocked by gas from the previous round fired. Rounds are contained in a magazine fitted to the rifle. It uses high velocity rounds which make a louder noise when fired.You have to go through initial weapon training on this weapon and pass your WHTs. As you progress through the syllabus and gain skill and confidence, you will have the opportunity to fire in the fire trench (standing in a pit with your elbows to the ground), kneeling and sitting positions.
** Cadet Marksman
When you are trained on one of the rifles you will be able to go onto a range and fire them in aim of achieving one of your marksmanship levels. These levels get progressively more challenging as they go on so you will need to get practising.
